// <auto-generated />
using InstagramProject.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstagramProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241023110437_Instaproject")]
    partial class Instaproject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("InstagramProject.Models.Instachild", b =>
                {
                    b.Property<int>("InstaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstaId");

                    b.HasIndex("PId");

                    b.ToTable("Instachild");
                });

            modelBuilder.Entity("InstagramProject.Models.Instaparent", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PId");

                    b.ToTable("Instaparent");
                });

            modelBuilder.Entity("InstagramProject.Models.Instachild", b =>
                {
                    b.HasOne("InstagramProject.Models.Instaparent", "Instaparent")
                        .WithMany("Instachild")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instaparent");
                });

            modelBuilder.Entity("InstagramProject.Models.Instaparent", b =>
                {
                    b.Navigation("Instachild");
                });
#pragma warning restore 612, 618
        }
    }
}
